# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16d18b47295fe4075b318a185ab92d393a8fa5df61f6e43c5fdd10eabc622b1234c6a181baf43ab1da1e7ab2a770449e32bfabc926c09f4fa0991890870a2631

test:
  secret_key_base: 1cf3ce8c2aea4886b93b160cd9496ca657abd5db24818ac894bcdf53eba8e6899f35675de0ff2435d45a6660708b1c3514264a93674f8ac932645d1a04c08663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
